# Generated by Django 5.2.11 on 2026-04-16 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("edc_he", "0014_alter_education_subject_visit_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="educationtype",
            options={
                "default_permissions": (
                    "add",
                    "change",
                    "delete",
                    "view",
                    "export",
                    "import",
                ),
                "ordering": ("display_index", "display_name"),
                "verbose_name": "Education type",
                "verbose_name_plural": "Education types",
            },
        ),
        migrations.AlterModelOptions(
            name="employmenttype",
            options={
                "default_permissions": (
                    "add",
                    "change",
                    "delete",
                    "view",
                    "export",
                    "import",
                ),
                "ordering": ("display_index", "display_name"),
                "verbose_name": "Employment type",
                "verbose_name_plural": "Employment types",
            },
        ),
        migrations.AlterModelOptions(
            name="ethnicities",
            options={
                "default_permissions": (
                    "add",
                    "change",
                    "delete",
                    "view",
                    "export",
                    "import",
                ),
                "ordering": ("display_index", "display_name"),
                "verbose_name": "Ethnicities",
                "verbose_name_plural": "Ethnicities",
            },
        ),
        migrations.AlterModelOptions(
            name="insurancetypes",
            options={
                "default_permissions": (
                    "add",
                    "change",
                    "delete",
                    "view",
                    "export",
                    "import",
                ),
                "ordering": ("display_index", "display_name"),
                "verbose_name": "Insurance Types",
                "verbose_name_plural": "Insurance Types",
            },
        ),
        migrations.AlterModelOptions(
            name="nationalities",
            options={
                "default_permissions": (
                    "add",
                    "change",
                    "delete",
                    "view",
                    "export",
                    "import",
                ),
                "ordering": ("display_index", "display_name"),
                "verbose_name": "Nationalities",
                "verbose_name_plural": "Nationalities",
            },
        ),
        migrations.AlterModelOptions(
            name="religions",
            options={
                "default_permissions": (
                    "add",
                    "change",
                    "delete",
                    "view",
                    "export",
                    "import",
                ),
                "ordering": ("display_index", "display_name"),
                "verbose_name": "Religions",
                "verbose_name_plural": "Religions",
            },
        ),
    ]
